    repoURL: https://github.com/Nick-Limber/k3s-gitops-config
    targetRevision: HEAD
    path: argocd/apps
    
    plugin:
      name: deploykf
      env:
        ## 2. Tell the plugin to fetch the official deployKF code
        - name: PARAM_SOURCE_VERSION
          value: "v0.1.5"
        ## 3. Your custom values
        - name: VALUES
          value: |
            argocd:
              appNamePrefix: "my-dkf-"
            # ... other overrides ...
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
