apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-argo-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Nick-Limber/k3s-gitops-config  # <-- Points to THIS repository
    targetRevision: HEAD
    path: argocd/apps # <-- Directory containing the child Application definitions (Part 2.3 below)
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd # Targets the namespace where the child Application resources will be created
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true