apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-specs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://airflow-helm.github.io/charts 
    chart: airflow

  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true