apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"

spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: spark-operator
  source:
    repoURL: https://github.com/kubeflow/spark-operator
    path: charts/spark-operator-chart
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true