apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-operator
  namespace: argocd
  
spec:
  project: default
  source:
    repoURL: https://github.com/Nick-Limber/k3s-gitops-config
    targetRevision: HEAD
    path: infrastructure/airflow
    helm:
      valueFiles:
        - values/values-airflow.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow

syncPolicy:
  automated:
    prune: true
    selfHeal: true