apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-dex
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubeflow/manifests.git
    path: common/dex/overlays/istio
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true