apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-install
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/kubeflow/manifests.git
    path: common/istio/istio-install/base
    targetRevision: master
    kustomize:
      patches:
      - target:
            kind: DaemonSet
            name: istio-cni-node
            patch: |-
            - op: replace
              path: /spec/template/spec/volumes/0/hostPath/path
              value: /var/lib/rancher/k3s/data/current/bin
            - op: replace
              path: /spec/template/spec/volumes/2/hostPath/path
              value: /var/lib/rancher/k3s/agent/etc/cni/net.d
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true