apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-install
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubeflow/manifests.git
    path: common/istio/istio-install/base
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true