apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-install
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubeflow/manifests.git
    path: common/istio/istio-install/base
    targetRevision: master
    kustomize:
      patches:
        - target:
            kind: Deployment
            name: istio-cni-node
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/env/name=CNI_CONF_DIR/value
              value: /var/lib/rancher/k3s/agent/etc/cni/net.d
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true