apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-pipelines
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: 'https://github.com/kubeflow/manifests.git'
    path: applications/pipeline/upstream/overlays/multi-user
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kubeflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Workflow
      jsonPointers:
        - /status