apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-mtls-fix
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Apply early so services are ready
spec:
  project: default
  source:
    repoURL: https://github.com/Nick-Limber/k3s-gitops-config
    targetRevision: HEAD
    path: argocd/configs/mtls # We will create this directory next
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true